# Generated by Django 4.1.7 on 2023-03-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('recieved', models.BooleanField(default=False)),
                ('state1', models.DecimalField(decimal_places=4, max_digits=10)),
                ('state2', models.DecimalField(decimal_places=4, max_digits=10)),
                ('state3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('state4', models.DecimalField(decimal_places=4, max_digits=10)),
                ('state5', models.DecimalField(decimal_places=4, max_digits=10)),
                ('state6', models.DecimalField(decimal_places=4, max_digits=10)),
                ('state7', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
